name: Install System Dependencies
description: Install System dependencies for Filecoin Lotus

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      run: |
        # List processes to enable debugging in case /var/lib/apt/lists/ is locked 
        ps aux
        sudo apt-get update -y
        sudo apt-get install -y ocl-icd-opencl-dev libhwloc-dev pkg-config
      shell: bash
    - if: runner.os == 'macOS'
      env:
        HOMEBREW_NO_AUTO_UPDATE: '1'
      run: |
        brew install hwloc pkg-config jq || true
        # Support both Intel (/usr/local) and Apple Silicon (/opt/homebrew)
        BREW_PREFIX=$(brew --prefix)
        echo "CPATH=${BREW_PREFIX}/include" | tee -a $GITHUB_ENV
        echo "LIBRARY_PATH=${BREW_PREFIX}/lib" | tee -a $GITHUB_ENV
        echo "CGO_LDFLAGS=-L${BREW_PREFIX}/lib" | tee -a $GITHUB_ENV
        echo "CGO_CFLAGS=-I${BREW_PREFIX}/include" | tee -a $GITHUB_ENV
      shell: bash
